from sqlalchemy import text
from sqlalchemy.orm import Session, DeclarativeBase, InstrumentedAttribute

def reset_table_id_seq(
    session: Session,
    entity: type[DeclarativeBase],
    entity_id_column: InstrumentedAttribute[int],
    next_id: int,
) -> None:
    """Reset the ID sequence of an entity table.

    Args:
        session (Session) - A SQLAlchemy Session
        entity (DeclarativeBase) - The SQLAlchemy Entity table to target
        entity_id_column (MappedColumn) - The ID column (should be an int column)
        next_id (int) - Where the next inserted, autogenerated ID should begin

    Returns:
        None"""
    table_name = entity.__tablename__
    id_column_name = entity_id_column.name
    sequence_name = f"{table_name}_{id_column_name}_seq"
    sql = text(f"ALTER SEQUENCE {sequence_name} RESTART WITH {next_id}")
    session.execute(sql)
    session.commit()
