version: "3"

services:
  httpd:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
      - csxl.unc.edu-ex03-node_modules:/workspace/frontend/node_modules
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - windir # Defined on Windows but not on other platforms
    deploy:
      resources:
        limits:
          memory: 2g
  db:
    image: postgres:15.2
    restart: unless-stopped
    env_file:
      - ../backend/.env
    ports:
      - "5434:5432"
    volumes:
      - csxl.unc.edu-ex03-postgres:/var/lib/postgresql/data

volumes:
  csxl.unc.edu-ex03-node_modules:
  csxl.unc.edu-ex03-postgres:
