"""Migration for 6-implement-backend-logic-for-storing-and-retrieving-profile-data

Revision ID: 477ae6e01953
Revises: 0eaf631b58c7
Create Date: 2024-05-13 23:57:59.671055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477ae6e01953'
down_revision = '0eaf631b58c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tags',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('name', sa.String(length=50), nullable=False, unique=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    # ### end Alembic commands ###